import './styles/reset.css';
import './styles/variables.css';
import './styles/layout.css';
import './styles/components.css';
import './styles/app.css';
import { renderHeader } from './components/header';
import { route, initRouter } from './router';
import { renderPlaces } from './pages/places';
import { renderPlaceDetail } from './pages/place-detail';
import { renderSchedule } from './pages/schedule';
import { renderProfile } from './pages/profile';
import { renderLogin } from './pages/login';
document.addEventListener('DOMContentLoaded', () => {
    renderHeader('app-header');
    route('/', renderPlaces);
    route('/places/:uid', renderPlaceDetail);
    route('/schedule', renderSchedule);
    route('/profile', renderProfile);
    route('/login', renderLogin);
    initRouter();
});
